#!/bin/sh

set -e

PWD=`pwd`

git submodule init
git submodule update

ln -s $PWD/vim ~/.vim
ln -s $PWD/vimrc ~/.vimrc
ln -s $PWD/vimrc.local ~/.vimrc.local
ln -s $PWD/vimrc.bundles ~/.vimrc.bundles
ln -s $PWD/vimrc.bundles.local ~/.vimrc.bundles.local

vim +PluginInstall +qall!

echo "Installation done, Enjoy it!"
